[package]
name = "indexed_data_file"
version = "0.6.5"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed data file. It uses mmap and avltiree."

repository = "https://github.com/OdenShirataki/indexed_data_file"

keywords = ["index","file","avltree","memmap","data"]
license = "MIT/Apache-2.0"

[dependencies]
avltriee={ path="../avltriee" , version="0.6" }
file_mmap={ path="../file_mmap" , version="0.1" }
