[package]
name = "idx_sized"
version = "0.10.13"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed data file. It uses mmap and avltiree."

repository = "https://github.com/OdenShirataki/idx_sized"

keywords = ["index","file","avltree","memmap","data"]
categories = ["database"]
license = "MIT/Apache-2.0"

[dependencies]
avltriee="0.14"
file_mmap="0.4"
