[package]
name = "indexed_data_file"
version = "0.2.0"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed data file. It uses mmap and tri-avltree."

repository = "https://github.com/OdenShirataki/indexed_data_file"

keywords = ["index","file","avltree","memmap","data"]
license = "MIT"

[dependencies]
tri_avltree={ path="../tri_avltree" , version="0.2" }
file_mmap={ path="../file_mmap" , version="0.1" }
