[package]
name = "idx_sized"
version = "0.10.10"
edition = "2021"

authors = ["Oden Shirataki <oden.srtk@gmail.com>"]

description = "Indexed data file. It uses mmap and avltiree."

repository = "https://github.com/OdenShirataki/idx_sized"

keywords = ["index","file","avltree","memmap","data"]
license = "MIT/Apache-2.0"

[dependencies]
avltriee={ path="../avltriee" , version="0.14" }
file_mmap={ path="../file_mmap" , version="0.4" }
